In [1]:
#cau 1
def sum (a,b):
    return a + b

sum(1,2)

3

In [13]:
#cau 2
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([[1,2,3]])

print("The Rank of a Matrix: ", np.linalg.matrix_rank(arr))

The Rank of a Matrix:  2


In [15]:
#cau 3
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = arr + 3
print(arr)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
#cau 4
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.transpose(arr)
print(arr)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
#cau 5
import numpy as np
arr = np.array([[1,2]])

norm_x = np.linalg.norm(arr)
normalize = arr/norm_x
print("Vector x:", arr)
print("Norm of x:", norm_x)
print("Normalized x:", normalize)

Vector x: [[1 2]]
Norm of x: 2.23606797749979
Normalized x: [[0.4472136  0.89442719]]


In [21]:
#cau 6
import numpy as np
a = np.array([[10,15]])
b = np.array([[8,2]])
c = np.array([[1,2,3]])

print(a-b)
print(a+b)


[[ 2 13]]
[[18 17]]


In [30]:
#cau 7
import numpy as np

# Định nghĩa hai ma trận
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Thực hiện phép nhân ma trận
result_matrix = np.dot(matrix1, matrix2)

# Hiển thị kết quả
print("Ma trận 1:")
print(matrix1)
print("\nMa trận 2:")
print(matrix2)
print("\nKết quả của phép nhân ma trận:")
print(result_matrix)



Ma trận 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Ma trận 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Kết quả của phép nhân ma trận:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [29]:
#cau 8
import numpy as np
A = np.array([[2,4,9],[3,6,7]])
print("The Rank of a Matrix: ", np.linalg.matrix_rank(A))
print("the value of 7 in A: ", A[1,2])
print("the second column in A: ", str([row[1] for row in A]))

The Rank of a Matrix:  2
the value of 7 in A:  7
the second column in A:  [4, 6]


In [41]:
#cau 9
import numpy as np
import random

x = np.random.randint(-10, 10, size=(3, 3))
print(x)

[[  8   7  -5]
 [  2   9   3]
 [-10   5   3]]


In [43]:
#cau 10
import numpy as np

x = np.identity(4)
print(x)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [54]:
#cau 11
import numpy as np
import random

x = np.random.randint(1, 10, size=(3, 3))
print(x)

#use command
trace  = np.trace(x)
print(trace)
print()

#use for loop
result = 0
for i in range(len(x)):
    result += x[i][i]
print(result)


[[8 5 1]
 [4 6 9]
 [6 3 8]]
22

22
